[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "photidy"
version = "0.1.0"
description = "A simple photo organisation tool"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Rob Webb", email = "rdawebb@gmail.com"}
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0,<10.0",
    "pytest-cov>=7.0,<8.0",
    "icecream>=2.1,<3.0",
    "maturin>=1.4,<2.0"
]