[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "photidy"
version = "0.2.0"
description = "A simple photo organisation tool"
requires-python = ">=3.11"
authors = [
    {name = "Rob Webb", email = "rdawebb@gmail.com"}
]
dependencies = [
    "appdirs>=1.4,<2.0",
    "pyside6>=6.8,<6.9",
    "typer>=0.21.0,<1.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0,<10.0",
    "pytest-cov>=7.0,<8.0",
    "icecream>=2.1,<3.0",
    "maturin>=1.4,<2.0",
    "pre-commit>=4.5.0,<5.0.0",
    "ruff>=0.14.10,<1.0.0",
    "ty>=0.0.9,<0.1.0",
]

[project.scripts]
photidy = "src.cli.cli:app"

[tool.maturin]
module-name = "_photidy"
python-packages = ["src"]
manifest-path = "rust/_photidy/Cargo.toml"
